// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Используем переменные окружения для URL и ключа
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Проверка наличия переменных окружения
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Ошибка: Отсутствуют переменные окружения для Supabase');
  console.error('Убедитесь, что файл .env.local содержит VITE_SUPABASE_URL и VITE_SUPABASE_ANON_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL as string, 
  SUPABASE_PUBLISHABLE_KEY as string
);